apiVersion: certmanager.k8s.io/v1alphav1
kind: Certificate
metadata:
  name: simple-k8s-com-tls # Replace with your domain name
spec:
  secretName: simple-k8s-com # Replace with your domain name
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: simple-k8s.com # Replace with your domain name
  dnsNames:
    - simple-k8s.com
    - www.simple-k8s.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - simple-k8s.com
          - www.simple-k8s.com