apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    certmanager.k8s.io/clsuter-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
  - hosts:
    - simple-k8s.com
    - www.simple-k8s.com
    secretName: simple-k8s-com
  rules:
  - host: simple-k8s.com
    http:
      paths:
      - path: /
        backend:
          serviceName: client-cluster-ip-service
          servicePort: 5000
      - path: /api/
        backend:
          serviceName: server-cluster-ip-service
          servicePort: 5000
  - host: www.simple-k8s.com # Why though? 
    http:
      paths:
      - path: /
        backend:
          serviceName: client-cluster-ip-service
          servicePort: 5000
      - path: /api/
        backend:
          serviceName: server-cluster-ip-service
          servicePort: 5000  